### ISSUE TITLE
Exception thrown on AttributeError (bad values call?)

### ISSUE THREAD

**Issue by brandonjbjelland** [brandoconnor/flickr-album-per-camera#1]
Processing stopped with the following:

```
processing photo 4561 of 6826: 4596249797
Traceback (most recent call last):
  File "org_photos.py", line 72, in <module>
    print('Skipping photo with insufficient metadata.')
  File "org_photos.py", line 60, in main
    primary_photo_id=photo_id,
AttributeError: 'unicode' object has no attribute 'values'
```

**Comment by brandonjbjelland** [comment]
This is resolved with cee50b1.
